package application;

import javafx.fxml.FXML;


import javafx.scene.control.Button;
import javafx.scene.shape.ArcTo;
import javafx.scene.shape.ClosePath;
import javafx.scene.shape.MoveTo;
import javafx.scene.shape.Path;

import javafx.scene.control.ToggleGroup;

import javafx.event.ActionEvent;

import javafx.scene.control.RadioButton;

import javafx.scene.input.MouseEvent;

import javafx.scene.shape.Polygon;

import javafx.scene.shape.Polyline;

import javafx.scene.layout.Pane;

public class TestPageController {
	private enum ShapeType{ POLYLINE, POLYGON, PATH};
	@FXML
	private RadioButton polygon;
	@FXML
	private ToggleGroup toggleGroupB;
	@FXML
	private RadioButton polyline;
	@FXML
	private RadioButton path;
	@FXML
	private Button ClearButtonSelected;
	@FXML
	private Pane drawingAreaPane;
	@FXML
	private Polyline polylineF;
	@FXML
	private Polygon polygonF;
	@FXML
	private Path pathF;
	
	private ShapeType shapeType=ShapeType.POLYLINE;
	private boolean sweepFlag=true;
	public void initialize() {
		polygon.setUserData(ShapeType.POLYGON);
		polyline.setUserData(ShapeType.POLYLINE);
		path.setUserData(ShapeType.PATH);
		//displayShape();
	}

	// Event Listener on RadioButton[#polygon].onAction
	@FXML
	public void polygonButton(ActionEvent event) {
		// TODO Autogenerated
		shapeType = (ShapeType) toggleGroupB.getSelectedToggle().getUserData();
		//polygonF.setVisible(shapeType==ShapeType.POLYGON);
		displayShape();
	}
	// Event Listener on RadioButton[#polyline].onAction
	@FXML
	public void polylineButton(ActionEvent event) {
		// TODO Autogenerated
		shapeType=(ShapeType)toggleGroupB.getSelectedToggle().getUserData();
		//polylineF.setVisible(shapeType==ShapeType.POLYLINE);
		displayShape();
	}
	// Event Listener on RadioButton[#path].onAction
	@FXML
	public void pathButton(ActionEvent event) {
		// TODO Autogenerated
		shapeType=(ShapeType)toggleGroupB.getSelectedToggle().getUserData();
		//pathF.setVisible(shapeType==ShapeType.PATH);
		displayShape();
	}
	public void displayShape() {
		polylineF.setVisible(shapeType==ShapeType.POLYLINE);
		polygonF.setVisible(shapeType==ShapeType.POLYGON);
		pathF.setVisible(shapeType==ShapeType.PATH);
	}
	// Event Listener on Button[#ClearButtonSelected].onAction
	@FXML
	private void clearButtonSelected(ActionEvent event) {
		// TODO Autogenerated
		polylineF.getPoints().clear();
		polygonF.getPoints().clear();
		pathF.getElements().clear();
	}
	// Event Listener on Pane[#drawingAreaPane].onMouseClicked
	@FXML
	public void dAMClicked(MouseEvent event) {
		// TODO Autogenerated
		//polyline.getPoints().addAll(event.getX(), event.getY());
		polylineF.getPoints().addAll(event.getX(), event.getY());
		polygonF.getPoints().addAll(event.getX(), event.getY());
		if(pathF.getElements().isEmpty()) {
			pathF.getElements().add(new MoveTo(event.getX(), event.getY()));
			pathF.getElements().add(new ClosePath());
		}else {
			ArcTo arcTo=new ArcTo();
			arcTo.setX(event.getX());
			arcTo.setY(event.getY());
			arcTo.setRadiusX(100.0);
			arcTo.setRadiusY(100.0);
			arcTo.setSweepFlag(sweepFlag);
			sweepFlag=!sweepFlag;
			pathF.getElements().add(pathF.getElements().size()-1, arcTo);
		}
	}
	// Event Listener on Pane[#drawingAreaPane].onMouseDragged
	@FXML
	public void drawingAreaMouseDragged(MouseEvent event) {
		// TODO Autogenerated
	}
}
